"""esquema inicial

Banco novo: esta migração cria todas as tabelas. Banco criado antes do Alembic (pelo antigo
create_all): o app o adota, marcando-o nesta revisão sem executar nada (app/db/migrations.py).

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 07:21:12.708356
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('last_profiles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_email'), ['email'], unique=False)

    op.create_table('asset_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_key', sa.String(length=255), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('bpcs_number', sa.String(length=100), nullable=True),
    sa.Column('sap_number', sa.String(length=100), nullable=True),
    sa.Column('praca', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_key', name='uq_asset_stores_store_key')
    )
    with op.batch_alter_table('asset_stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_stores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stores_praca'), ['praca'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stores_store_key'), ['store_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_stores_store_name'), ['store_name'], unique=False)

    op.create_table('oidc_login_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    with op.batch_alter_table('oidc_login_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_login_requests_expires_at'), ['expires_at'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_id'), ['id'], unique=False)

    op.create_table('assistant_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('n8n_session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('climate_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('capacity_btu', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.String(length=50), nullable=True),
    sa.Column('refrigerant_gas', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['asset_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('climate_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_climate_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_climate_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_climate_assets_store_id'), ['store_id'], unique=False)

    op.create_table('fire_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('extinguisher_agent', sa.String(length=80), nullable=True),
    sa.Column('capacity', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('hydrostatic_test_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['asset_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fire_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fire_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_fire_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fire_assets_store_id'), ['store_id'], unique=False)

    op.create_table('oidc_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('email_at_link', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('bpcs_number', sa.String(), nullable=True),
    sa.Column('sap_number', sa.String(), nullable=True),
    sa.Column('praca', sa.String(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('solution_text', sa.Text(), nullable=True),
    sa.Column('signature_status', sa.String(), nullable=True),
    sa.Column('signed_pdf_url', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('in_attendance_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('requester', sa.String(), nullable=True),
    sa.Column('analyst_responsible', sa.String(), nullable=True),
    sa.Column('non_approval_reason', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_ticket'), ['ticket'], unique=True)

    op.create_table('store_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('custom_document_type', sa.String(length=150), nullable=True),
    sa.Column('document_number', sa.String(length=150), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['asset_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('store_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_documents_store_id'), ['store_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('id_token_hint', sa.Text(), nullable=True),
    sa.Column('sid', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('profiles', sa.JSON(), nullable=False),
    sa.Column('snapshot_refreshed_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_failed_since', sa.DateTime(), nullable=True),
    sa.Column('refresh_attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_sid'), ['sid'], unique=False)
        batch_op.create_index('ix_user_sessions_token_hash', ['session_token_hash'], unique=False)

    op.create_table('water_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.String(length=50), nullable=True),
    sa.Column('last_filter_change', sa.Date(), nullable=True),
    sa.Column('next_filter_change', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['asset_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_water_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_assets_store_id'), ['store_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_chars', sa.Integer(), nullable=True),
    sa.Column('response_chars', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('assistant_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_messages_conversation_id'))

    op.drop_table('assistant_messages')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('water_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_assets_store_id'))
        batch_op.drop_index(batch_op.f('ix_water_assets_id'))
        batch_op.drop_index(batch_op.f('ix_water_assets_asset_code'))

    op.drop_table('water_assets')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_token_hash')
        batch_op.drop_index(batch_op.f('ix_user_sessions_sid'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('store_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_documents_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_documents_id'))

    op.drop_table('store_documents')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_ticket'))
        batch_op.drop_index(batch_op.f('ix_services_id'))

    op.drop_table('services')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_created_at'))

    op.drop_table('security_events')
    op.drop_table('oidc_identities')
    with op.batch_alter_table('fire_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fire_assets_store_id'))
        batch_op.drop_index(batch_op.f('ix_fire_assets_id'))
        batch_op.drop_index(batch_op.f('ix_fire_assets_asset_code'))

    op.drop_table('fire_assets')
    with op.batch_alter_table('climate_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_climate_assets_store_id'))
        batch_op.drop_index(batch_op.f('ix_climate_assets_id'))
        batch_op.drop_index(batch_op.f('ix_climate_assets_asset_code'))

    op.drop_table('climate_assets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))

    op.drop_table('assistant_conversations')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('oidc_login_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_login_requests_expires_at'))

    op.drop_table('oidc_login_requests')
    with op.batch_alter_table('asset_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_stores_store_name'))
        batch_op.drop_index(batch_op.f('ix_asset_stores_store_key'))
        batch_op.drop_index(batch_op.f('ix_asset_stores_praca'))
        batch_op.drop_index(batch_op.f('ix_asset_stores_id'))

    op.drop_table('asset_stores')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_email'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
